### ISSUE TITLE
IE 11: Access is denied error

### ISSUE THREAD

**Issue by JeffJacobson** [WSDOT-GIS/elc-js#4]
While running the [demo](http://wsdot-gis.github.io/elc-js/demo/ArcGisElcUI/) in IE and submitting either of the forms, to the user it appears that nothing happened. However the following error is written to the console.

```javascript
{
   [functions]: ,
   __proto__: { },
   description: "Access is denied.
",
   message: "Access is denied.
",
   name: "Error",
   number: -2147024891,
   stack: "Error: Access is denied.

   at RouteLocator.prototype.findRouteLocations (http://wsdot-gis.github.io/elc-js/elc/main.js:592:4)
   at Anonymous function (http://wsdot-gis.github.io/elc-js/elc/elc-ui/arcgis-elc-ui.js:115:5)"
}
```
Note that this issue doesn't appear when running from localhost via Visual Studio & IIS Express.

**Comment by JeffJacobson** [comment]
This issue apparently only occurs within WSDOT intranet. When accessing from other locations the error does not occur. It looks like a setting in our configuration of IE is causing the issue.
